%
% Get info about past jobs from SLURM accounting database
%
% Copyright © 2025 Ernst Strüngmann Institute (ESI) for Neuroscience
% in Cooperation with Max Planck Society
%
% SPDX-License-Identifier: BSD-3-Clause
%
function jobInfo = sacct_query(jobId)
% SACCT_QUERY - Query info about job from SLURM accounting database

% see man sacct for possible fields
fields = {...
    'AllocCPUs', ...
    'AllocNodes', ...
    'Account', ...
    'Cluster', ...
    'CPUTime', ...
    'ExitCode', ...
    'Elapsed', ...
    'ElapsedRaw', ...
    'End', ...
    'GID', ...
    'Group', ...
    'JobID', ...
    'MaxRSS', ... % Maximum resident set size of all tasks in job.
    'MaxVMSize', ... % Maximum Virtual Memory size of all tasks in job.
    'MaxDiskRead', ...
    'MaxDiskWrite', ...
    'NodeList', ...
    'Partition', ...
    'QOS', ...
    'ReqMem', ...
    'ReqTres', ...
    'Start', ...
    'Timelimit', ...
    'UID', ...
    'User' ...
    'State', ...
    };

structAlloc = [fields; cell(1, numel(fields))];
jobInfo = struct(structAlloc{:});


outputFormat = sprintf('%s,', fields{:});
outputFormat(end) = '';

cmd = [sprintf('sacct -o %s --noconvert -P -n -j ', outputFormat) sprintf('%d.0,', jobId)];


[status, output] = system_out_to_disk(cmd);
assert(status == 0, 'Could not retreive job status of job %d', jobId)

% parse output
output = strsplit(output, char(10));
for iJob = 1:length(jobId)
    jobOutput = output{iJob};
    jobOutput = strsplit(strrep(jobOutput, char(10), ''), '|', 'CollapseDelimiters', false);
    jobInfo(iJob) = cell2struct(jobOutput, fields,2);
end



